name: Common Build

on:
  workflow_call:
    inputs:
      prefix:
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  REPOSITORY_NAME: jupyter-docker
  IMAGE_NAME: codio/codio-jupyter
  ECR_REGISTRY: public.ecr.aws/o0g3m8o6

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::878986216776:role/Github/GithubECRPublicUploadRole_${{ env.REPOSITORY_NAME }}
          role-session-name: GithubAction

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and use a new builder instance
        run: |
          docker buildx create --name ga-builder --use

      - name: Set image tags
        id: meta
        run: |
          ECR_REGISTRY="${{ env.ECR_REGISTRY }}"
          SHA_SHORT=${{ inputs.prefix }}-$(echo ${{ github.sha }} | cut -c1-7)

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            IMAGE_TAG="${{ inputs.prefix }}-${{ github.event.pull_request.head.ref }}"
          else
            IMAGE_TAG="${{ inputs.prefix }}-${{ github.event.inputs.tag || 'latest' }}"
            TIMESTAMP=${{ inputs.prefix }}-$(date +%Y%m%d)
            echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
          fi

          echo "ecr_registry=${ECR_REGISTRY}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "sha_short=${SHA_SHORT}" >> $GITHUB_OUTPUT

          TAGS="${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG},${ECR_REGISTRY}/${IMAGE_NAME}:${SHA_SHORT}"

          if [ "${{ github.event_name }}" != "pull_request" ]; then
            TAGS="${TAGS},${ECR_REGISTRY}/${IMAGE_NAME}:${TIMESTAMP}"
          fi

          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        timeout-minutes: 30
        with:
          context: ./${{ inputs.prefix }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          builder: ga-builder
          cache-from: type=registry,ref=${{ steps.meta.outputs.ecr_registry }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ steps.meta.outputs.ecr_registry }}/${{ env.IMAGE_NAME }}:cache

      - name: Image summary
        run: |
          {
            echo "### Docker Image Published :rocket:"
            echo "event name: ${{ github.event_name }}"
            echo ""
            echo "**Registry:** ${{ steps.meta.outputs.ecr_registry }}"
            echo "**Image:** ${IMAGE_NAME}"
            echo ""
            echo "**Tags:**"
            echo "- \`${{ steps.meta.outputs.image_tag }}\`"
            echo "- \`${{ steps.meta.outputs.timestamp || 'Timestamp tag is not available for PR' }}\`"
            echo "- \`${{ steps.meta.outputs.sha_short }}\`"
            echo ""
            echo "**Pull command:**"
            echo "\`\`\`bash"
            echo "docker pull ${{ steps.meta.outputs.ecr_registry }}/${IMAGE_NAME}:${{ steps.meta.outputs.image_tag }}"
            echo "\`\`\`"
          } | tee -a $GITHUB_STEP_SUMMARY
